//
// Created by clement.mathe on 12/04/2024.
//

#ifndef T_IOT_902_SENSORSENSEI_DEVICETYPE_H
#define T_IOT_902_SENSORSENSEI_DEVICETYPE_H

enum DeviceType {
    ESP32_DEVKIT,
    ESP8266_DEVKIT,
    ARDUINO_UNO,
    ARDUINO_NANO,
};

#endif //T_IOT_902_SENSORSENSEI_DEVICETYPE_H
