//
// Created by clement.mathe on 12/04/2024.
//

#ifndef T_IOT_902_SENSORSENSEI_SENSORTYPE_H
#define T_IOT_902_SENSORSENSEI_SENSORTYPE_H

enum SensorType {
    UNKNOWN,
    TEMPERATURE,
    HUMIDITY,
    AIR_QUALITY,
    SOUND,
    PRESSURE,
    ALTITUDE,
};

#endif //T_IOT_902_SENSORSENSEI_SENSORTYPE_H
